In [1]:
import numpy as np

In [2]:
a =np.array(4)

In [3]:
a

array(4)

In [4]:
a.ndim

0

In [5]:
arr= np.array([1,2,3,45,873])

In [6]:
arr

array([  1,   2,   3,  45, 873])

In [7]:
arr.ndim

1

In [8]:
mat = np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
mat

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
mat.ndim

2

In [11]:
n =np.array([[[1,2,3],[23,34,45],[34,45,677]]])

In [12]:
n

array([[[  1,   2,   3],
        [ 23,  34,  45],
        [ 34,  45, 677]]])